### PR TITLE
A quick fix to add the index for verify function

### PR DESCRIPTION
**Pull request by elong0527**

### CODE REVIEW

**Comment by tonyfischetti** [comment]
Hi!
First question: is it ok that the same `...` arguments are used for both the success *and* error functions?

**Comment by elong0527** [comment]
Hi!

I think you are right. In general the argument should be different in success and fail function.

**Comment by tonyfischetti** [comment]
Cool.
Also, some of the tests that `verify` is supposed to do don't make sense in terms of keeping track of indices... certain things like "does that dataset have more that 10 rows?", etc...

**Comment by elong0527** [comment]
Totally agree! Maybe an option to show indices or not serve the need. And the default is "No".

**Comment by tonyfischetti** [comment]
I'd be into that!

**Comment by tonyfischetti** [comment]
Hi, did you want to implement the thing where you can specify whether you want to show the indices?

**Comment by tonyfischetti** [comment]
If you do, I can re-open this, otherwise, it's definitely on my radar :)

**Comment by tonyfischetti** [comment]
Hey, just tested it. I'm not sure the indices thing will work out. For example, several of the testthat tests fail because it's trying to run `nrow` on a list, which verify should take.
If you have any ideas, I'd be happy to re-open this issue :)

**Comment by tonyfischetti** [comment]
I have great news :)
I implemented something that I think would work for you in commit b18be10c8cdc
It includes and index just like you wanted for `verify` to match the error data.frames from the rest of the verbs. The error data.frames thing is pretty cool! You should check it out :)
I'll be submitting to CRAN shortly

**Pull request closed without merging**
